[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gocardless-proxy/:splat"
  status = 200

[[redirects]]
  from = "/refresh-token"
  to = "/.netlify/functions/gocardless-refresh-token"
  status = 200
