[build]
  functions = "netlify/functions"
  command = "npm install"

[dev]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gocardless-proxy"
  status = 200
